### ISSUE TITLE
Readme contradicts actual files

### ISSUE THREAD

**Issue by konstin** [juliuste/gemeindeverzeichnis#6]
The readme says this module contains 6 different files, though after installing I only got one (`data.ndjson`).

**Comment by derhuerst** [comment]
This is probably unintuitive, but **GitHub shows the readme as of `master`, whereas [npm shows the readme from the latest release](https://www.npmjs.com/package/gemeindeverzeichnis)**. You should therefore refer to npm for documentation.

@juliuste I think it would be good to publish the latest `master` to npm. Also, what do you think about an automatic CI-driven publishing process, [like with `db-stations`](https://github.com/derhuerst/db-stations/blob/b0f1d1d07390cf8181cadb9f3cf2fa04ecf054da/.travis.yml)?

**Comment by juliuste** [comment]
Published to npm 🙂

As to an automated release process: Feel free to PR 😄

**Comment by derhuerst** [comment]
I guess this issue can either get closed or renamed then.

**Comment by konstin** [comment]
Thanks!
